# Terminal colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color*:Tc"

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-yank'


set -s set-clipboard on
# set -s set-clipboard external

# select and copy with vim motions
# set vi-mode
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -T copy-mode MouseDragEnd1Pane send -X copy-selection-no-clear
bind-key -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

# catppuccin config
# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_text " #( echo \#{pane_current_path} | sed \"s|$HOME|~|\" | xargs basename )"
set -g @catppuccin_window_current_text " #( echo \#{pane_current_path} | sed \"s|$HOME|~|\" )"

# config for date_time module
set -g @catppuccin_date_time_text " %a %h %d | %I:%M %p"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# config for host module
# set -g @catppuccin_host_text "#(whoami)@#h"

# initialize (must be last)
run '~/.tmux/plugins/tpm/tpm
