return {
  { treesitter = { "go" }, mason = { "gopls" }, lsp = { "gopls" } },
  { treesitter = { "python" }, mason = { "pyright", "black" }, lsp = { "pyright" } },
  { treesitter = { "javascript", "typescript", "tsx", "html", "css" }, mason = { "vtsls", "eslint_d", "prettier", "prettierd" }, lsp = { "vtsls" } },
  { treesitter = { "bash" }, mason = { "shellcheck", "shfmt", "bash-language-server" }, lsp = { "bashls" } },
  { treesitter = { "rust" }, mason = { "rust-analyzer" }, lsp = { "rust_analyzer" } },
  { treesitter = { "json" }, mason = { "jq", "jsonlint" } },
  { treesitter = { "java" }, mason = { "jdtls", "java-debug-adapter", "java-test", "google-java-format" }, lsp = { "jdtls" } },
  { treesitter = { "lua" }, mason = { "stylua", "lua-language-server" }, lsp = { "lua_ls" } },
  { treesitter = { "yaml" }, mason = { "yq", "yamllint", "yaml-language-server", "actionlint" }, lsp = { "yamlls" } },
  { treesitter = { "terraform" }, mason = { "terraform-ls" }, lsp = { "terraformls" } },
  { treesitter = { "cpp", "c" }, mason = { "clangd" }, lsp = { "clangd" } },
  { mason = { "markdownlint", "markdown-oxide" }, lsp = { "markdown_oxide" } },
  { mason = { "docker-language-server" }, lsp = { "docker_language_server" } },
}
